name: reviewdog

on:
    pull_request:
      types: [ opened, synchronize ]

jobs:
  markdown-lint:
    name: runner / markdown-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: markdown-lint
        uses: reviewdog/action-markdownlint@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          markdownlint_flags: '--disable MD013 --' # disable line length rule
